name: Node.js CI

on:
  push:
    branches: [ "master" ]  # Change this from "main" to "master"
  pull_request:
    branches: [ "master" ]  # Change this from "main" to "master"

jobs:
  test:
    name: Running Node Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: List directory contents
      run: ls -la
      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        
    - name: Debug information
      run: |
        pwd
        cat package.json
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test
